blog/urls.py
from django.conf.urls import patterns, url, include
from blog.views import BlogListView, PostView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
	url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
	url(r'^comments/', include('django_comments.urls')),
	(r'^tinymce/', include('tinymce.urls')),
	url(r'^tinymce/zinnia/', include('zinnia_tinymce.urls')),
	url(r'^blog/?$', BlogListView.as_view(), name="Blog"),
	url(r'^blog/categoria/(?P<category>[-_\w]+)/?$', BlogListView.as_view(), name='Category'),
	url(r'^blog/(?P<slug>[-_\w]+)/$', PostView.as_view(), name='Post'),
	)
	

if settings.LOCAL:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.conf.urls import patterns, url
from portal import views
from portal.sitemap import *
from portal.views import (PortalHomeView, PortalContatoView, PortalPhotoLivroView, PortalPhotoLembrancaView,
							PortalPhotoGramView, PortalPhotoProjecaoView, PortalPhotoEmpresaView, enviar_contato,
							receber_lead)

sitemaps = {
    'pages':PortalSitemap(['Portal', 'PhotoLivro', 'PhotoLembranca', 'PhotoGram', 'PhotoProjecao',
     'PhotoEmpresa', 'Contato']),
}

urlpatterns = patterns('',
	url(r'^/?$',  PortalHomeView.as_view(), name="Portal"),
	url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
	url(r'^photolivro/?$',  PortalPhotoLivroView.as_view(), name="PhotoLivro"),
	url(r'^photolembranca/?$',  PortalPhotoLembrancaView.as_view(), name="PhotoLembranca"),
	url(r'^photogram/?$',  PortalPhotoGramView.as_view(), name="PhotoGram"),
	url(r'^photoprojecao/?$',  PortalPhotoProjecaoView.as_view(), name="PhotoProjecao"),
	url(r'^photoempresa/?$',  PortalPhotoEmpresaView.as_view(), name="PhotoEmpresa"),
	url(r'^contato/?$',  PortalContatoView.as_view(), name="Contato"),
	url(r'^enviar_contato/?$',  enviar_contato, name="EnviarContato"),
	url(r'^receber_lead/?$',  receber_lead, name="ReceberLead"),
	)

portal/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

EVENT_CHOICES = [
    ['1', 'Casamento'],
    ['2', u'Aniversário'],
    ['3', 'Formatura'],
    ['4', 'Corporativo'],
    ['5', 'Outro']
]

class Contact(models.Model):
    class Meta:
        verbose_name = u"Contato"
        verbose_name_plural = u"Contatos"

    name = models.CharField(max_length=256, verbose_name=u"Nome")
    email = models.EmailField(max_length=128)
    tel = models.CharField(max_length=32, verbose_name=u"Telefone")
    city = models.CharField(null=True, blank=True, max_length=128, verbose_name=u"Cidade")
    state = models.CharField(null=True, blank=True, max_length=2, verbose_name=u"Estado")

    def __unicode__(self):
        return self.name

class Budget(models.Model):
    class Meta:
        verbose_name = u"Orçamento"
        verbose_name_plural = u"Orçamentos"

    event_type = models.CharField(max_length=1, choices=EVENT_CHOICES, verbose_name=u"Tipo de evento")
    contact = models.ForeignKey(Contact, verbose_name=u"Contato")
    date = models.DateField(verbose_name=u"Data do evento")
    message = models.TextField(verbose_name=u"Mensagem")
    date_created = models.DateField(verbose_name=u"Data do contato",  default=timezone.now)

    def __unicode__(self):
        return self.contact.name

class PodioConfig(models.Model):
	client_id = models.CharField(max_length=256)
	client_secret = models.CharField(max_length=512)
	username = models.CharField(max_length=256)
	password = models.CharField(max_length=256)
	app_id = models.CharField(max_length=256)

portal/forms.py
# -*- coding: utf-8 -*-
from django import forms
from municipios.widgets import SelectMunicipioWidget
from portal.models import EVENT_CHOICES

class ContactForm(forms.Form):
	service_type = forms.ChoiceField(
		# widget=forms.TextInput(
		#     attrs={"placeholder": u"Cidade"}),
		widget=forms.RadioSelect,
		choices = EVENT_CHOICES,
		required=True, 
		label="QUAL TIPO DE EVENTO?"
	)
	municipios = forms.IntegerField(
		label=u"QUAL A LOCALIZAÇÃO DO EVENTO?",
		widget=SelectMunicipioWidget,
		required=True
	)
	name = forms.CharField(
		label="PREENCHA OS CAMPOS ABAIXO",
		widget=forms.TextInput(
            attrs={"placeholder": u"Seu nome (obrigatório)"}), 
		required=True,
	)
	tel = forms.CharField(
		label="",
		widget=forms.TextInput(
            attrs={"placeholder": u"Seu telefone (obrigatório)"}), 
		required=True,
	)
	email = forms.EmailField(
		label="",
		widget=forms.TextInput(
            attrs={"placeholder": u"Seu e-mail (obrigatório)"}), 
		required=True
	)
	date_start = forms.DateField(
		label="",
		widget=forms.TextInput(
		attrs={"class": "datepicker", "placeholder": u"Data do evento"}),
		required=True
	)
	message = forms.CharField(
		widget=forms.Textarea(
            attrs={"placeholder": u"Sua mensagem"}),
		label="",
		required=True
	)

portal/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, TemplateView, DetailView, FormView
from forms import ContactForm
from django.core.mail import send_mail
from municipios.models import Municipio, UF
from django.db.models import Q
from portal.models import Contact, Budget, PodioConfig
from pypodio2 import api
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import HttpResponse

# Create your views here.

class PortalHomeView(TemplateView):
    template_name = "bootstrap_home.html"

class PortalPhotoLivroView(TemplateView):
	template_name = "photolivro.html"

class PortalPhotoLembrancaView(TemplateView):
	template_name = "photolembranca.html"

class PortalPhotoGramView(TemplateView):
	template_name = "photogram.html"

class PortalPhotoProjecaoView(TemplateView):
	template_name = "photoprojecao.html"

class PortalPhotoEmpresaView(TemplateView):
	template_name = "photoempresa.html"

class PortalContatoView(TemplateView):
	template_name = "contato.html"

	def get_context_data(self, **kwargs):
		context = super(PortalContatoView, self).get_context_data(**kwargs)
		context['contact_form'] = ContactForm()

		return context

def enviar_contato(request):
		# if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
			service_type = 	form.cleaned_data['service_type']
			municipios = 	form.cleaned_data['municipios']
			name = 			form.cleaned_data['name']
			tel = 			form.cleaned_data['tel']
			email = 		form.cleaned_data['email']
			date_start = 	form.cleaned_data['date_start']
			message = 		form.cleaned_data['message']

			a = Municipio.objects.get(id_ibge = municipios)

			cidade = a.nome
			uf = a.uf.nome

			msg = u"O usuário '"+name+"', email: "+email+", telefone: "+tel+", envi'ou um contato pelo site.\n"
			msg+= u"Tipo de evento: "
			if service_type == 1:
				msg+="Casamento"
			elif service_type == 2:
				msg+="Aniversário"
			elif service_type == 3:
				msg+="Formatura"
			elif service_type == 4:
				msg+="Corporativo"
			else:
				msg+="Outro"
			msg+="\n"
			msg+= u"Cidade: "+cidade+", Estado: "+uf+"\n"
			msg+= "Dia do evento: "+str(date_start)+"\n"
			msg+= u"Mensagem: "+message

			try:
				contato = Contact.objects.get(Q(email=email))
			except Contact.DoesNotExist:
				contato = Contact(
					name = name,
					email = email,
					tel = tel,
					city = cidade,
					state = a.uf.uf,
				)
				contato.save()

			orcamento = Budget(
				event_type = service_type,
				contact = contato,
				date = date_start,
				message = message,
			)
			orcamento.save()
			# podio = PodioConfig.objects.get(pk=1)

			# c = api.OAuthClient(
			#     podio.client_id,
			#     podio.client_secret,
			#     podio.username,
			#     podio.password,    
			# )

			# item = {
			# 	"fields":[{
			# 		"company-or-organisation": name,
			# 		"email": email,
			# 		"sales-contact": 2758134,
			# 		"tipo-de-evento": 1,
			# 		"status2": 0,
			# 		"next-follow-up": {"start":"2015-03-11 00:00:00","end":"2112-01-31 00:00:00"},
			# 		"street-address": "",
			# 		"city": cidade,
			# 		"state-provins-or-territory": a.uf.uf,
			# 		"address": ""
			# 	}]
			# }
			# print item

			# c.Item.create(int(podio.app_id), item)

			send_mail("Orçamento PhotoPlay", msg, 'noreply@photoplay.com.br', 
				['equipe@photoplay.com.br', 'contato@photosite.webfactional.com'] )


			return render(request, 'contato_sucesso.html')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'contato.html', {'contact_form': form})

@csrf_exempt
def receber_lead(request):
    	# if this is a POST request we need to process the form data
	if request.method == 'POST':
        # create a form instance and populate it with data from the request:
		form = json.loads(request.body)

		nome = form['nome']
		tel = form['tel']
		email = form['email']
		tipo = form['tipo']
		data = form['data']
		estado = form['estado']
		cidade = form['cidade']
		como_conheceu = form['como_conheceu']
		codigo = form['codigo']

		msg = u"Lead recebido pelo site do Fottorama:\n"
		msg+= u"Nome: '"+nome+"'\n"
		msg+= u"Telefone: '"+tel+"'\n"
		msg+= u"Email: '"+email+"'\n"
		msg+= u"Tipo de evento: '"+tipo+"'\n"
		if tipo == 1:
			msg+="Casamento\n"
		elif tipo == 2:
			msg+="Corporativo\n"
		elif tipo == 3:
			msg+="Aniversário\n"
		elif tipo == 4:
			msg+="Formatura\n"
		elif tipo == 5:
			msg+="Universitário\n"
		else:
			msg+="Outro\n"
		
		msg+= u"Data: '"+data+"'\n"
		msg+= u"Estado: '"+estado+"'\n"
		msg+= u"Cidade: '"+cidade+"'\n"
		msg+= u"Como conheceu: "
		if como_conheceu == 1:
			msg+="'Vi propaganda no Facebook'\n"
		elif como_conheceu == 2:
			msg+="'Busquei no Google'\n"
		elif como_conheceu == 3:
			msg+="'Em uma Feira de Noivas'\n"
		elif como_conheceu == 7:
			msg+="'Revista'\n"
		elif como_conheceu == 4:
			msg+="'Vi em um evento e gostei'\n"
		elif como_conheceu == 5:
			msg+="'Um amigo me recomendou'\n"
		else:
			msg+="'Por outro meio'\n"
		msg+= u"Código Promocional: '"+codigo+"'\n"

		send_mail("Orçamento PhotoPlay", unicode(msg), 'noreply@photoplay.com.br', 
		['equipe@photoplay.com.br', 'contato@photosite.webfactional.com'] )

		return HttpResponse("200 ok")

portal/templates/contato.html
{% extends 'bootstrap.html' %}


{% block title %}
Contato
{% endblock %}

{% block head %}
<meta content="Entre em contato com a PhotoPlay e peça já um orçamento para o seu evento ficar ainda mais divertido." name="description">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$.datepicker.regional['br'] = {
            closeText: 'Fechar',
            prevText: 'Anterior',
            nextText: 'Próximo',
            currentText: 'Hoje',
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho',
            'Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev.','Mar','Abr','Mai','Jun',
            'Jul','Ago','Set','Out','Nov','Dez'],
            dayNames: ['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'],
            dayNamesShort: ['Dom','Seg','Ter.','Qua','Qui','Sex','Sab'],
            dayNamesMin: ['D','S','T','Q','Q','S','S'],
            weekHeader: 'Semana',
            dateFormat: 'dd/mm/yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''};
        $.datepicker.setDefaults($.datepicker.regional['br']);
        $( ".datepicker" ).datepicker( $.datepicker.regional[ "fr" ] );

        $('#municipios_uf option:contains("--")').prop('disabled', true).text("Estado");
        $('#id_municipios option:contains("--")').prop('disabled', true).text("Cidade");

        $("#id_tel").mask("(99) 9999?9-9999");


		$("#id_tel").on("blur", function() {
		    var last = $(this).val().substr( $(this).val().indexOf("-") + 1 );
		    
		    if( last.length == 3 ) {
		        var move = $(this).val().substr( $(this).val().indexOf("-") - 1, 1 );
		        var lastfour = move + last;
		        
		        var first = $(this).val().substr( 0, 9 );
		        
		        $(this).val( first + '-' + lastfour );
		    }
		});
	});
	
</script>
<style type="text/css">
	#header{
		height: 100px;
		background: none;z
	}
	#header_container{
		background: -moz-linear-gradient(top, rgba(255,255,255,0.2) 0%, rgba(0,0,0,0.2) 100%), rgba(33, 63, 154, 1); /* FF3.6+ */;
		background: -moz-linear-gradient(top, rgba(255,255,255,0.2) 0%, rgba(0,0,0,0.2) 100%), rgba(33, 63, 154, 1); /* FF3.6+ */
		background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,0.2)), color-stop(100%,rgba(0,0,0,0.2))), rgba(33, 63, 154, 1); /* Chrome,Safari4+ */
		background: -webkit-linear-gradient(top, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(33, 63, 154, 1); /* Chrome10+,Safari5.1+ */
		background: -o-linear-gradient(top, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(33, 63, 154, 1); /* Opera 11.10+ */
		background: -ms-linear-gradient(top, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(33, 63, 154, 1); /* IE10+ */
		background: linear-gradient(to bottom, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(33, 63, 154, 1); /* W3C */	
		position: fixed;
		z-index: 999;
	}
	#parallax1{
		height: 200px;
		width: 1400px;
		position: relative;
		background-image: url("{{STATIC_URL}}/img/parallax1_produtos.jpg");
	}
	.cHeader{
		background-color: rgb(80,184,72);
		height: 100px; 
		width: 1400px;
	}
	.cHeaderContent{
		width: 1000px;
		left: 50%;
		margin-left: -500px;
		position: relative;
	}
	.cHeader ul{
		list-style: outside none none;
		margin: 0;
		padding: 0;
	}
	.cHeader li{
		float: left;
		margin: 30px 11px 0 0;
	}
	.cHeader h1{
		color: white;
		font-size: 32px;
		margin: 0;
	}
	.cContato_img{
		width:  370px;

	}
	form>label[for=id_service_type_0]{
		font-family: "Montserrat",sans-serif;
		font-size: 20px;
		color: #213f9a;
		font-weight: 900;
		}
	form>label[for=id_name]{
		font-family: "Montserrat",sans-serif;
		font-size: 20px;
		color: #213f9a;
		font-weight: 900;	
	}
	form>label[for=id_municipios]{
		font-family: "Montserrat",sans-serif;
		font-size: 20px;
		color: #213f9a;
		font-weight: 900;	
	}
	form ul{
		padding: 0;
		margin: 16px 0;
	}
	form li>label{
		font-weight:normal;
	}
	form li{
		font-family: "Lato",sans-serif;
		font-size: 14px;
		color: #3a3a3a;
		font-weight: 300;
		list-style: outside none none;
	}
	form textarea{
		padding: 10px 0 0 20px;
	}
	form input{
		padding: 0px 0 0 20px;
	}
	#id_name{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 50px;
    	width: 97%;
    	margin-top: 20px;
	}
	#id_tel{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 50px;
    	width: 97%;
    	margin-top: 20px;
	}
	#id_email{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 50px;
    	width: 97%;
    	margin-top: 20px;
	}
	#id_date_start{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 50px;
    	width: 97%;
    	margin-top: 20px;
	}
	#id_message{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 100px;
    	width: 97%;
    	margin: 20px 0 30px 0;
	}
	#municipios_uf{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 50px;
    	width: 19%;
    	margin: 20px 10px 20px 0;
    	float: left;
	}
	#id_municipios{
		border: 1px solid #b5b5b5;
    	border-radius: 10px;
   		color: #3a3a3a;
    	font-family: "Lato",sans-serif;
    	font-size: 14px;
    	font-weight: 300;
    	height: 50px;
    	width: 76% !important;
    	margin: 20px 0;
	}
	form input[type="submit"]{
		background: -moz-linear-gradient(top, rgba(255,255,255,0.2) 0%, rgba(0,0,0,0.2) 100%), rgba(80, 184, 72, 0.70); /* FF3.6+ */
		background: -moz-linear-gradient(top, rgba(255,255,255,0.2) 0%, rgba(0,0,0,0.2) 100%), rgba(80, 184, 72, 0.70); /* FF3.6+ */
		background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,0.2)), color-stop(100%,rgba(0,0,0,0.2))), rgba(80, 184, 72, 0.70); /* Chrome,Safari4+ */
		background: -webkit-linear-gradient(top, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(80, 184, 72, 0.70); /* Chrome10+,Safari5.1+ */
		background: -o-linear-gradient(top, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(80, 184, 72, 0.70); /* Opera 11.10+ */
		background: -ms-linear-gradient(top, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(80, 184, 72, 0.70); /* IE10+ */
		background: linear-gradient(to bottom, rgba(255,255,255,0.2) 0%,rgba(0,0,0,0.2) 100%), rgba(80, 184, 72, 0.70); /* W3C */
		border: 2px solid white;
		border-radius: 10px;
		color: white;
		font-family: "Montserrat",sans-serif;
		font-size: 16px;
		font-weight: 900;
		height: 60px;
		width: 280px;
		box-shadow: 0 -5px 0 rgba(0,0,0,0.2) inset;
		-moz-box-shadow: 0 -5px 0 rgba(0, 0, 0, 0.2) inset;
		-webkit-box-shadow: 0 -5px 0 rgba(0, 0, 0, 0.2) inset;
	}
	form input[type="submit"]:hover{
	}
	form input[type="submit"]:active{
		box-shadow: none;
		background: rgba(80, 184, 72, 0.70); /* FF3.6+ */
	}
	ul.errorlist{
		margin: 0;
	}
	.errorlist li{
		color: red;
	}
	.margin_60{
		margin: 60px 0;
	}
	.button_center-xs{
		padding: 0;
		margin: 0 auto;
		display: block;
	}
	/* Small devices (tablets, 768px and up) */
	@media (min-width: 768px) { 
		form li>label{
			margin: 0;
		}
		.button_center-xs{
			margin: 0;
		}
	}

</style>
{% endblock %}


{% block content %}
<div class="row div_limiter"> 
	<div class="margin_60 col-sm-12">
		<form class="" action="/enviar_contato/" method="post">
			{% csrf_token %}
			{{ contact_form.media }}
			{{contact_form}}
			<input class="button_center-xs" type="submit" value="Enviar Contato"/>
		</form>
	</div>
	<div class="margin_60 col-sm-12">
		<h3 style="font-size: 28px; font-weight: 700; color: #213f9a;">DEIXE SEU EVENTO</h1>
		<h3 style="font-size: 38px; font-weight: 700; color: #213f9a;">MAIS DIVERTIDO!</h1>

		<h1 style="font-size: 18px; font-weight: 700; margin-top: 60px; color: #213f9a;">FOTOS ILIMITADAS</h1>
		<p class="ppadrao">Seus convidados tiram fotos à vontade e levam 
		para casa uma lembrança personalizada.
		</p>

		<h1 style="font-size: 18px; font-weight: 700; margin-top: 60px; color: #213f9a;">IMAGENS NO TELÃO EM TEMPO REAL</h1>
		<p class="ppadrao">Mais interatividade com projeção das fotos tiradas
		no  totem e das fotos publicadas no Instagram com a hashtag do seu evento.
		</p>

		<img class="center-block" style="width:100%; max-width:462px;" src="{{STATIC_URL}}img/img7.png">
	</div>
</div>


{% endblock %}